# Generated by Django 2.1.4 on 2019-04-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
