# Generated by Django 2.1.4 on 2019-04-20 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0002_auto_20190420_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
