# Generated by Django 2.1.4 on 2019-04-20 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0003_auto_20190420_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cin',
            field=models.IntegerField(),
        ),
    ]
