# Generated by Django 2.1.4 on 2019-04-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0004_auto_20190420_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='infos_sessions',
            new_name='infoSessions',
        ),
    ]
