# Generated by Django 2.1.4 on 2019-04-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0005_auto_20190420_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reunions',
            field=models.ManyToManyField(blank=True, related_name='reunions', to='JetPlateform.Reunion'),
        ),
    ]
