# Generated by Django 2.1.4 on 2019-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0009_auto_20190420_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
