# Generated by Django 2.1.4 on 2019-04-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0010_auto_20190420_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='condidatures',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='infoSessions',
        ),
        migrations.AddField(
            model_name='condidature',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCondidat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infosession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInfosession', to=settings.AUTH_USER_MODEL),
        ),
    ]
