# Generated by Django 2.1.4 on 2019-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0011_auto_20190421_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidature',
            name='user',
        ),
        migrations.RemoveField(
            model_name='infosession',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='condidatures',
            field=models.ManyToManyField(blank=True, related_name='condidatures', to='JetPlateform.Condidature'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='infoSessions',
            field=models.ManyToManyField(blank=True, related_name='infoSessions', to='JetPlateform.InfoSession'),
        ),
    ]
