# Generated by Django 2.1.4 on 2019-04-21 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0012_auto_20190421_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='condidatures',
        ),
        migrations.AddField(
            model_name='customuser',
            name='condidatures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condidatures', to='JetPlateform.Condidature'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='infoSessions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='infoSessions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoSessions', to='JetPlateform.InfoSession'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reunions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reunions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='JetPlateform.Reunion'),
        ),
    ]
