# Generated by Django 2.1.4 on 2019-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetPlateform', '0013_auto_20190421_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidature',
            name='fichiers',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='isAccepted',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='condidatures',
        ),
        migrations.AddField(
            model_name='customuser',
            name='condidatures',
            field=models.ManyToManyField(related_name='user', to='JetPlateform.Condidature'),
        ),
    ]
